[package]
name = "mizupay"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xdf2ac204ef758ae05809c7171716f5ded8e6182a3f37c71473d69e4444bdcbd7"

[dependencies]
# Sui dependency removed; it is automatically included by the Sui CLI
Sui = { git = "https://github.com/MystenLabs/sui.git", rev = "fbb68879cbd1", subdir = "crates/sui-framework/packages/sui-framework" }
# lbtc = { git = "https://github.com/lombard-finance/sui-move-contracts", subdir = "move/lbtc", rev = "main" }
# consortium = { git = "https://github.com/lombard-finance/sui-move-contracts", subdir = "move/consortium", rev = "main" }
# bascule = { git = "https://github.com/lombard-finance/sui-move-contracts", subdir = "move/bascule", rev = "main" }

[addresses]
mizupay = "0x0" 
# lbtc_v1 = "0x3e8e9423d80e1774a7ca128fccd8bf5f1f7753be658c5e645929037f7c819040"
# lbtc_v4 = "0x818430a456ff977f7320f78650d19801f90758d200a01dd3c2c679472c521357"